### ISSUE TITLE
ngAnimate

### ISSUE THREAD

**Issue by yvesvanbroekhoven** [fd/fd-angular-core#2]
What are the steps to load ngAnimate in an app? Is it already included in fd-angular-core or do you need to install it separately?

Thanks!

**Comment by pieterbeulque** [comment]
Hi,

Since we're bundling Angular inside the fd-angular-core package it's not that easy to figure out :)

What you want to do is install `github:angular/bower-angular-animate` through JSPM:

`$ jspm install github:angular/bower-angular-animate@1.4.8`

1.4.8 is the Angular version we're currently bundling. We might bump to 1.5.1 when it's out.

In your JSPM `config.js`, change the map `angular/bower-angular-animate` to `ng-animate` (not neccessary but more clear).

Also make sure its dependency is as follows:

```
    "github:angular/bower-angular-animate@1.4.8": {
      "angular": "github:angular/bower-angular@1.4.8"
    },
```

in the `config.js` file. It appears it tries to load bower-angular@1.5.0, which gives us two complete versions of Angular in our bundle, which you want to avoid at all costs.

Now, in your main application file, `import 'ng-animate';` (or `anguler/bower-angular-animate` if you didn't change the mapping).

Change your main `bootstrap()` function like this:

```
export function main () {
    return bootstrap(AppController, [ 'ng-animate' ]);
}
```

---

That's all there is to it! Add your `.ng-enter` & other magic sparkles in your styles and walla-ka-zam!

Disclaimer: the above code builds & correctly bundles `ng-animate`. I yet have to try out actual animations.

**Comment by yvesvanbroekhoven** [comment]
Awesome! Thanks for the explanation :).

**Comment by yvesvanbroekhoven** [comment]
Tiny typo in the bootstrap function. Just tested and this works as should:

```
export function main () {
    return bootstrap(AppController, 'ngAnimate');
}
```

**Comment by pieterbeulque** [comment]
:+1: thanks
